# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradb',
            name='TimeStamp',
            field=models.DateTimeField(),
        ),
    ]
